❯ vi ../terraform.tfvars
ARG ARCH=""
FROM ${ARCH}debian:10
 
RUN apt-get update ; \
    apt-get install -y gnupg apt-transport-https  wget ca-certificates; \


RUN echo "deb [trusted=yes] https://zmrepo.zoneminder.com/debian/release-1.36 buster/" >> etc/apt/sources.list; \
    wget -O - https://zmrepo.zoneminder.com/debian/archive-keyring.gpg | apt-key add -; \
    apt-get update; apt-get -y install zoneminder; \
RUN apt-get remove --purge -y $BUILD_PACKAGES $(apt-mark showauto) && rm -rf /var/lib/apt/lists/*; \
    adduser www-data video; systemctl enable zoneminder.service; a2enconf zoneminder; a2enmod rewrite

RUN ln -sf /usr/share/zoneminder/www/fonts /usr/share/zoneminder/www/skins/classic/css/fonts

# Setup Volumes
VOLUME /var/cache/zoneminder/events /var/cache/zoneminder/images /var/lib/mysql /var/log/zm

# Expose http port
EXPOSE 80

# Configure entrypoint
COPY utils/entrypoint.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
